# _target_: hulc.datasets.arnold_disk_dataset.ArnoldDiskDataset
# key: "lang"
# save_format: "npz"
# batch_size: 32
# min_window_size: 20
# max_window_size: 32
# proprio_state: ${datamodule.proprioception_dims}
# obs_space: ${datamodule.observation_space}
# skip_frames: 1
# pad: true
# lang_folder: "lang_paraphrase-MiniLM-L3-v2"
# aux_lang_loss_window: 8
# num_workers: 2
_target_: hulc.datasets.arnold_disk_dataset.ArnoldDiskDataset
key: "lang"
save_format: "npz"
batch_size: 2
min_window_size: 20
max_window_size: 32
skip_frames: 24
proprio_state: ${datamodule.proprioception_dims}
obs_space: ${datamodule.observation_space}
pad: true
lang_folder: "lang_paraphrase-MiniLM-L3-v2"
num_workers: 2
aux_lang_loss_window: 8

