defaults:
  - datasets: arnold
  - transforms: rand_shift
  - proprioception_dims: arnold_robot_full
  - observation_space: arnold
_target_: hulc.datasets.arnold_data_module.ArnoldDataModule
_recursive_: false
root_data_dir: ???
action_space: 7
# action_max: [1., 1., 1., 1., 1., 1., 1.,]
# action_min: [-1., -1., -1., -1., -1., -1., -1]
action_max : [2.8973, 1.7628, 2.8973, -0.0698, 2.8973, 3.7525, 2.8973]
action_min : [-2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973]
shuffle_val: false
